version: "3"
services: 
  app:
    image: spring-boot:latest
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - db
  db:
    image: mysql
    restart: always
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=notes_app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=secretpassword 
