name: spring-boot Docker Image CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  docker:
      runs-on: ubuntu-latest
      steps:
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            platforms: linux/amd64
            push: true
            file: Dockerfile
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot:prod-v${{ github.run_number }}
        -
          name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
          
#         - name: Download new image and run new containers
#           uses: JimCronqvist/action-ssh@master
#           with:
#             hosts: 'ubuntu@ec2-52-207-24-140.compute-1.amazonaws.com'
#             privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
#             debug: false
#             command: |
#               sudo docker-compose -f /home/ubuntu/django-demo/docker-compose.yml down
#               sudo docker-compose  -f /home/ubuntu/django-demo/docker-compose.yml pull 
#               sudo docker image prune -f
#               sudo docker-compose -f /home/ubuntu/django-demo/docker-compose.yml up -d